version: '3'

tasks:
  dev_infra:
    cmds:
      - sh ./scripts/start_dev_env.sh
  test:
    cmds: 
      - sh ./scripts/test.sh
  run:user_service:
    cmds:
      - go run "d:\Multimedia Project\Code\Server\cmd\user_service\main.go"
  gen:protobuf:
    cmds:
      - protoc --proto_path=protos "protos/asset.proto" --go_out=lib/protos/asset --go_opt=paths=source_relative --go-grpc_out=lib/protos/asset --go-grpc_opt=paths=source_relative
      - protoc --proto_path=protos "protos/user.proto" --go_out=lib/protos/user --go_opt=paths=source_relative --go-grpc_out=lib/protos/user --go-grpc_opt=paths=source_relative